PatientBookingApp/PatientBookingApp/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PatientBookingApp.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

PatientBookingApp/PatientBookingApp/Pages/AddBook.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PatientBookingApp.Pages
{
    public class AddBookModel : PageModel
    {
        private readonly AppDbContext _db;
        public AddBookModel(AppDbContext db)
        {
            _db = db;
        }

        [TempData]
        public string Message { get; set; }

        [BindProperty]
        public TimeSlot TimeSlot { get; set; }

        [BindProperty]
        public Treatment Treatment { get; set; }


        [BindProperty]
        public Book Book { get; set; }
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

                    _db.TimeSlots.Add(TimeSlot);
                    _db.Treatments.Add(Treatment);
                    Book.TimeSlotId = TimeSlot.Id;
                    Book.TreatmentId = Treatment.Id;
                    _db.Books.Add(Book);
                    await _db.SaveChangesAsync();
                    Message = $"{Book} Added sucessfully!";
                    return RedirectToPage("/Index");

        }

    }
}

PatientBookingApp/PatientBookingApp/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PatientBookingApp.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

PatientBookingApp/PatientBookingApp/Pages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace PatientBookingApp.Pages
{
    public class EditModel : PageModel
    {
        private readonly AppDbContext _db;
        public EditModel(AppDbContext db)
        {
            _db = db;
        }
        [BindProperty]
        public TimeSlot TimeSlot { get; set; }
        [BindProperty]
        public Treatment Treatment { get; set; }
        [BindProperty]
        public Book Book { get; set; }
        public async Task<IActionResult> OnGetAsync(int id)
        {
            Book = await _db.Books.FindAsync(id);
            if(Book == null)
            {
                RedirectToPage("/Index");
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _db.Attach(TimeSlot).State = EntityState.Modified;
            _db.Attach(Treatment).State = EntityState.Modified;

            _db.Attach(Book).State = EntityState.Modified;
            try
            {

               
                await _db.SaveChangesAsync();
            }

            catch (DbUpdateConcurrencyException)
            {
                throw new Exception($"Book {Book.BookingId} not Found!");
            }
            return RedirectToPage("./Index");
        }

    }
}

PatientBookingApp/PatientBookingApp/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PatientBookingApp.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

PatientBookingApp/PatientBookingApp/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PatientBookingApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly AppDbContext _db;
        public IndexModel(AppDbContext db)
        {
            _db = db;
        }

        public IList<Book> Books { get; private set; }
        public IList<Treatment> Treatments { get; private set; }
        public IList<TimeSlot> TimeSlots { get; private set; }

        public string Message { get; set; }
          public async Task OnGetAsync(string searchString)
          {

              var books = from m in _db.Books
                           select m;
              books = books.Where(g => g.IsDeleted.Equals(false));
              if (!String.IsNullOrEmpty(searchString))
              {
                  books = books.Where(s => s.Name.Contains(searchString) || s.Mobile.Contains(searchString));
              }



              Books = await books.ToListAsync();











            //  Books = await _db.Books.AsNoTracking().ToListAsync();

          }


        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            var book = await _db.Books.FindAsync(id);
            if(book != null)
            {
                book.IsDeleted = true;
            
                await _db.SaveChangesAsync();
            }
            return RedirectToPage();

        }

    }
}

PatientBookingApp/PatientBookingApp/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

PatientBookingApp/PatientBookingApp/Pages/AddBook.cshtml
@page
@model PatientBookingApp.Pages.AddBookModel
@{
    ViewData["Title"] = "AddBook";
}

<h2>AddBook</h2>
<form method="post">
    <div asp-validation-summary="All"></div>
    <div>Name: <input type="text" width="40" asp-for="Book.Name"  placeholder="Enter your full name please!"/></div>
    <div> Mobile:<input asp-for="Book.Mobile" type="tel" placeholder="07xx-xxx-xxx" /></div>
    <div><input asp-for="Book.Email" placeholder="Enter your Email" /></div>
    <div>Date: <input asp-for="Book.BookedDate" type="date"  placeholder="Choose a Date"/> </div>
    <div> Treatment: <input asp-for="Treatment.TreatmentTitle" type="text" /></div> 
    
    <div > 
        
        TimeSlot: 
        <select asp-for="TimeSlot.TimeSlotTitle">

            <option value=9>9:00 AM - 10:00 AM</option>
            <option value=10>10:00 AM - 11:00 AM</option>
            <option value=11>11:00 AM - 12:00 PM</option>
            <option value=12>12:00 PM - 1:00 PM</option>
        </select> 
    </div>






    <div>Note: <input asp-for="Book.Note" placeholder="Send us a feed pack " /></div>
    <div><input asp-for="Book.IsDeleted" value="false" type="hidden" /></div>
    <div> <input type="submit" value="Add Book" /></div>

</form>

PatientBookingApp/PatientBookingApp/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PatientBookingApp/PatientBookingApp/Pages/Edit.cshtml
@page "{id:int}"
@model PatientBookingApp.Pages.EditModel
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit Book @Model.Book.BookingId</h2>
<form method="post">
<div asp-validation-summary="All"></div>
    <input asp-for="Book.BookingId" type="hidden" />
    <input asp-for="TimeSlot.Id" type="hidden" readonly />
    <input asp-for="Treatment.Id" type="hidden"  readonly/>
    <div>
        <div> <label asp-for="Book.Name"> Name: <input asp-for="Book.Name" /></label></div>
        <div><label asp-for="Book.Mobile">Mobile:  <input asp-for="Book.Mobile" /> </label>
        </div>
        <div>
            <label asp-for="Book.BookedDate"> Date: <input asp-for="Book.BookedDate" /> </label>
        </div>
        <div>
            <label asp-for="Book.Note"> Note: <input asp-for="Book.Note" /></label>
        </div>
        <div>
            <label asp-for="TimeSlot.TimeSlotTitle">
                Time Slot:
                <select asp-for="Treatment.TreatmentTitle">
                    <option value=9>9:00 AM - 10:00 AM</option>
                    <option value=10>10:00 AM - 11:00 AM</option>
                    <option value=11>11:00 AM - 12:00 PM</option>
                    <option value=12>12:00 PM - 1:00 PM</option>
                </select>
            </label>
        </div> 
        <label asp-for="Treatment.TreatmentTitle">  Treatent: <input asp-for="Book.Treatment"  type="text" /></label>
        </div>
    <div>
        
        <input asp-for="Book.Email" readonly hidden />
        
        
        
       


    </div>

    <div>
        <button type="submit">Save Changes</button>
    </div>
</form>

PatientBookingApp/PatientBookingApp/Pages/Index.cshtml
@page 
@model IndexModel
@{
    ViewData["Title"] = "Books List";
}
<br />
<br />
<form>
    <p>

        Title: <input type="search" name="SearchString">
        <input type="submit" value="Search" />
        <a asp-page="/AddBook"><img src="~/images/Button_Only_-_Red_Cross_Logo.jpg" width="50" height="50" /></a>
    </p>
</form>
<br />
<br />

<form method="post">
    <div>
        <h3> @Model.Message</h3>

    </div>


    <div asp-validation-summary="All"></div>
    <table class="table">
        <thead>
            <tr>
                <th width="10">ID</th>
                <th width="20"> Name</th>
                <th width="20"> Mobile</th>
                <th width="20">Date</th>
                <th width="20"> Email</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var Book in Model.Books)
    {
                /*
        if (Book.IsDeleted == false)
        {
        }
        */

        <tr>
            <td width=" 10">@Book.BookingId</td>
            <td width=" 20">@Book.Name</td>
            <td width="20">@Book.Mobile</td>
            <td width="20" >@Book.BookedDate.ToLongDateString()</td>
            <td width="20">@Book.Email</td>
            <td width="10">
                <a asp-page="./Details" asp-route-id="@Book.BookingId"><img src="~/images/information-2-512.png" height="20" width="20" /></a>

                <a asp-page="./Edit" asp-route-id="@Book.BookingId"><img src="~/images/edit-icon-pencil_244589.png" height="20" width="20" /></a>

                <button class="Delete" name="DeleteButton" id="DelButton" type="submit" asp-page-handler="delete" asp-route-id="@Book.BookingId"><img src="~/images/delete-512.png" width="20" he.pngight="20" /></button>



            </td>

        </tr>


}


        </tbody>
    </table>


    <br />

   
    <br />
    <br />
</form>

PatientBookingApp/PatientBookingApp/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PatientBookingApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">PatientBookingApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - PatientBookingApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>